# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/presto/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so \
	vendor/pantech/presto/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/pantech/presto/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

# Prebuilt libraries	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/lib/libbcc.so:system/lib/libbcc.so \
	vendor/pantech/presto/proprietary/lib/libdvm.so:system/lib/libdvm.so \
	vendor/pantech/presto/proprietary/lib/libgenlock.so:system/lib/libgenlock.so \
	vendor/pantech/presto/proprietary/lib/libmemalloc.so:system/lib/libmemalloc.so \
	vendor/pantech/presto/proprietary/lib/liboverlay.so:system/lib/liboverlay.so \
	vendor/pantech/presto/proprietary/lib/libQcomUI.so:system/lib/libQcomUI.so \
	vendor/pantech/presto/proprietary/lib/hw/gralloc.msm8660.so:system/lib/hw/gralloc.msm8660.so

# Firmware	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/etc/firmware/cyttsp_8660_ffa.hex:system/etc/firmware/cyttsp_8660_ffa.hex \
	vendor/pantech/presto/proprietary/etc/firmware/cyttsp_8660_fluid_p2.hex:system/etc/firmware/cyttsp_8660_fluid_p2.hex \
	vendor/pantech/presto/proprietary/etc/firmware/cyttsp_8660_fluid_p3.hex:system/etc/firmware/cyttsp_8660_fluid_p3.hex \
	vendor/pantech/presto/proprietary/etc/firmware/dsps_fluid.b00:system/etc/firmware/dsps_fluid.b00 \
	vendor/pantech/presto/proprietary/etc/firmware/dsps_fluid.b01:system/etc/firmware/dsps_fluid.b01 \
	vendor/pantech/presto/proprietary/etc/firmware/dsps_fluid.b02:system/etc/firmware/dsps_fluid.b02 \
	vendor/pantech/presto/proprietary/etc/firmware/dsps_fluid.b03:system/etc/firmware/dsps_fluid.b03 \
	vendor/pantech/presto/proprietary/etc/firmware/dsps_fluid.mdt:system/etc/firmware/dsps_fluid.mdt

# Radio	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/bin/ks:system/bin/ks \
	vendor/pantech/presto/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/pantech/presto/proprietary/bin/qcks:system/bin/qcks \
	vendor/pantech/presto/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/pantech/presto/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/pantech/presto/proprietary/bin/rild:system/bin/rild \
	vendor/pantech/presto/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/pantech/presto/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/pantech/presto/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/pantech/presto/proprietary/lib/libidl.so:system/lib/libidl.so \
	vendor/pantech/presto/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/pantech/presto/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/pantech/presto/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/pantech/presto/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/pantech/presto/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/pantech/presto/proprietary/lib/libqueue.so:system/lib/libqueue.so \
	vendor/pantech/presto/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/pantech/presto/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	vendor/pantech/presto/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/pantech/presto/proprietary/lib/libril.so:system/lib/libril.so

#bins	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/bin/battery_charging:system/bin/battery_charging \
	vendor/pantech/presto/proprietary/bin/BCM43291A0_003.001.013.0141.0149.ORC.hcd:system/bin/BCM43291A0_003.001.013.0141.0149.ORC.hcd \
	vendor/pantech/presto/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
	vendor/pantech/presto/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/pantech/presto/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/pantech/presto/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/pantech/presto/proprietary/bin/port-bridge:system/bin/port-bridge

#gps	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
	vendor/pantech/presto/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	vendor/pantech/presto/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
	vendor/pantech/presto/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
	vendor/pantech/presto/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/pantech/presto/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so

# Audio	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
	vendor/pantech/presto/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
	vendor/pantech/presto/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/pantech/presto/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/pantech/presto/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so

#wifi	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
	vendor/pantech/presto/proprietary/etc/wl/bcm43291_apsta.bin:system/etc/wl/bcm43291_apsta.bin \
	vendor/pantech/presto/proprietary/etc/wl/bcm43291_mfg.bin:system/etc/wl/bcm43291_mfg.bin \
	vendor/pantech/presto/proprietary/etc/wl/bcm43291_p2p.bin:system/etc/wl/bcm43291_p2p.bin \
	vendor/pantech/presto/proprietary/etc/wl/bcm43291.bin:system/etc/wl/bcm43291.bin \
	vendor/pantech/presto/proprietary/etc/wl/nvram.txt:system/etc/wl/nvram.txt

#sky	
PRODUCT_COPY_FILES += \
	vendor/pantech/presto/proprietary/lib/libsky_access_nand.so:system/lib/libsky_access_nand.so \
	vendor/pantech/presto/proprietary/lib/libsky_aprlib.so:system/lib/libsky_aprlib.so \
	vendor/pantech/presto/proprietary/lib/libsky_bluetooth.so:system/lib/libsky_bluetooth.so \
	vendor/pantech/presto/proprietary/lib/libsky_ctrl_drv.so:system/lib/libsky_ctrl_drv.so \
	vendor/pantech/presto/proprietary/lib/libsky_dload.so:system/lib/libsky_dload.so \
	vendor/pantech/presto/proprietary/lib/libsky_fota_jni.so:system/lib/libsky_fota_jni.so \
	vendor/pantech/presto/proprietary/lib/libsky_fota_redbend.so:system/lib/libsky_fota_redbend.so \
	vendor/pantech/presto/proprietary/lib/libsky_fota.so:system/lib/libsky_fota.so \
	vendor/pantech/presto/proprietary/lib/libsky_rawdata.so:system/lib/libsky_rawdata.so \
	vendor/pantech/presto/proprietary/lib/libskyreset.so:system/lib/libskyreset.so \
	vendor/pantech/presto/proprietary/lib/libsky_rftest.so:system/lib/libsky_rftest.so \
	vendor/pantech/presto/proprietary/lib/libskytestclient.so:system/lib/libskytestclient.so \
#	vendor/pantech/presto/proprietary/lib/libsky_touch.so:system/lib/libsky_touch.so \
	vendor/pantech/presto/proprietary/lib/libsky_wifi.so:system/lib/libsky_wifi.so

